// Code generated by go-swagger; DO NOT EDIT.

// Package restapi go-rest-api
//
//	HTTP server in Go with Swagger endppoints definition
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - image/gif
//	  - application/json
//	  - text/plain
//
// swagger:meta
package restapi
