version: "3"

tasks:
  build:
      desc: Build the app
      cmds:
      - GOFLAGS=-mod=mod go build -o bin/cat-cli main.go
  
  run:
      desc: Run the app
      cmds:
      - GOFLAGS=-mod=mod go run main.go

  clean:
      desc: remove all downloaded *.gif files
      cmds:
      - rm *.gif
